[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/reuniones/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/proyectos/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/jornadas/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/recursos/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/casos/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/capacitaciones/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
